### ISSUE TITLE
IFTTT Probleme beim Geiger-Counter-Projekt

### ISSUE THREAD

**Issue by 4711engel** [SensorsIot/Geiger-Counter-RadiationD-v1.1-CAJOE-#11]
[Bild.pdf](https://github.com/SensorsIot/Geiger-Counter-RadiationD-v1.1-CAJOE-/files/3907236/Bild.pdf)
[Geigerzaehler-LCD-ESP-Server-IFTTT.zip](https://github.com/SensorsIot/Geiger-Counter-RadiationD-v1.1-CAJOE-/files/3907241/Geigerzaehler-LCD-ESP-Server-IFTTT.zip)
[IFTTT-APPLET.docx](https://github.com/SensorsIot/Geiger-Counter-RadiationD-v1.1-CAJOE-/files/3907249/IFTTT-APPLET.docx)

Ich habe es nun doch geschafft das benötigte APPLET zu erstellen. Der IFTTT-Key und der Event_Name ist im Sketch eingetragen und die Services und das sind active connected. Die App ist auf dem Handy installiert und aktiv. 
ThingSpeak habe ich noch nicht verwendet. Erst einmal IFTTT zum Laufen bringen. Ist alles neu für mich.
Ich füge meine Dateien an. 
Ich habe im Aufruf:    if (CPM > 30 ) IFTTT( EVENT_NAME, CPM);   mit einem geringeren Schwellenwert gearbeitet.
Trotzdem wird auf dem Handy keine Benachrichtigung ausgegeben, trotz Überschreitung des Wertes.
Habe ich etwas vergessen oder falsch gemacht?  Vielleicht hast Du eine Möglichkeit, dass ich Dateien mailen kann.

**Comment by SensorsIot** [comment]
Leider kann ich keinen solchen Support anbieten, da ich täglich mehrere solche Anfragen bekomme und YouTube nur mein Hobby ist. Ich bi sicher, dass du die Lösung mit etwas "pröbeln" findest. Ich müsste das genau gleich machen.
