### ISSUE TITLE
how to turn of audio

### ISSUE THREAD

**Issue by kibotu** [SensorsIot/Geiger-Counter-RadiationD-v1.1-CAJOE-#15]
thanks for sharing the specs, i've setup the counter and was able to measure with it

I was wondering if you have an idea how I could disable the speaker of the RadiationD-v1.1-CAJOE board?

**Comment by SensorsIot** [comment]
I assume you just have to desolder the buzzer..

**Comment by dr2okevin** [comment]
I have put some electrical tape over the speaker, makes it much less noticable. I would say the volume is now 1/3.

**Comment by tomgidden** [comment]
Isn't this what the J1 jumper is for?

**Comment by kibotu** [comment]
I'm not an electrician so I ended up ripping it up in the hope of not breaking it. I'm measuring the radiation in Berlin for about a year with it now.
