### ISSUE TITLE
IFTTT failed! error msg

### ISSUE THREAD

**Issue by twingall1** [SensorsIot/Geiger-Counter-RadiationD-v1.1-CAJOE-#18]
Hi, thanks for this excellent work and instructions.
All is good re display, and thingspeak communication. But problem getting IFTTT webhook connection to work.
I understand you are busy but hoped for some pointers in case i am missing something obvious to you.
I am using ESP32 Built-in OLED Board (Wemos Lolin32) (aliexpress: geiger counter kit)
So far i tried the following, with no success: 
-updating the fingerprint/thumbprint for https://ifttt.com/ in IFTTTWebhook.h  to 61:62:75:FA:EA:5F:64:95:4A:F6:09:0F:59:C9:0D:E7:1E:6D:66:A3
-compiled and uploaded (Arduino IDE 1.8.19) for both 'wemos lolin32' and 'sparkfun esp32 thing'
-on ifttt.com/create (webhooks); tried both 'receive a web request with a JSON payload' and 'Receive a web request' (...with the 'then that' being email notification)

To trigger the event, i am brushing the end of the tube connector, triggering many clicks and  !!alarm!! on the oLED display, but always in serial monitor it says 'IFTTT failed!'

Please tell me if you can think of any suggested avenues i might try in order to fix this/ workaround. I'm determined to get this working, and will report back my solution when i do.. just in need of a pointer. I'm somewhat scrabbling in the dark with limited experience here!

many thanks,
T

**Comment by SensorsIot** [comment]
This is an old project and IFTT changed a lot. Maybe this article helps: https://randomnerdtutorials.com/esp32-door-status-monitor-email/
