### ISSUE TITLE
Der PiGi eine weitere Möglichkeit?

### ISSUE THREAD

**Issue by Nordrunner01** [SensorsIot/Geiger-Counter-RadiationD-v1.1-CAJOE-#3]
Moin Andreas, oder Grüzi. :-)
Zu allerest: Vielen DANK für deine vielen tollen Beiträge!

Aufmerksam geworden durch ein Video auf YT von dir, möchte ich dich auf ein weiteres DIY-Projekt in Richtung Erfassung von Umweltstrahlung machen. Nämlich den [PiGi](https://apollo.open-resource.org/lab:pigi) .
Wie der Name unschwer vermuten lässt, ist der PiGi urprünglich für den Raspberry Pi konzipiert worden, lässt sich aber auch leicht mit anderen MCU`s betreiben.
Mehr Informationen zu dem PiGi findest Du/Ihr in unserem [WIKI](http://wiki.iot-usergroup.de/index.php/PiGi)
Bezugsmöglichkeiten für eine bestückte Platine ist in unserem [Forum](https://forum.iot-usergroup.de/t/bestellmoeglichkeit-pigi-platine-bestueckt/84/8) zu finden.
Wer lieber selbst besorgt und lötet findet auch die Zutatenlisten in den Quellen. ;-p

Soweit, so kurz.
Ich hoffe man liest sich. :-)

Gruß vom

Nordrunner

**Comment by SensorsIot** [comment]
Vielen Dank für die Infos!
