### ISSUE TITLE
How can I fix this?

### ISSUE THREAD

**Issue by omurozcan5** [SensorsIot/Geiger-Counter-RadiationD-v1.1-CAJOE-#4]
Hello
I tried to run these codes. I'm amateur. I made a connection like this. But in error
"exit status 1
Error compiling for board Arduino / Genuino Uno. "
How can I fix this?
https://ibb.co/hWSrOn
https://ibb.co/d6wJ3n

**Comment by SensorsIot** [comment]
Unfortunately I cannot do remote consulting :-(
