### ISSUE TITLE
Library issue IFTTTmaker 1.0.0

### ISSUE THREAD

**Issue by Tom-Neverwinter** [SensorsIot/Geiger-Counter-RadiationD-v1.1-CAJOE-#8]
https://github.com/witnessmenow/arduino-ifttt-maker

The IFTTT library requires older libraries to function:

https://github.com/witnessmenow/arduino-ifttt-maker/issues/5

"ArduinoJSON library version 5.13.2"

also for other users, dont forget: " ArduinoJson library written by Benoît Blanchon" ;)

**Comment by iotappstory** [comment]
You are right. Unfortunately, version 6 of the JSON lib does work completely differently .-(

**Comment by SensorsIot** [comment]
You are right. Unfortunately, version 6 of the JSON lib does work completely differently .-(
